### ISSUE TITLE
Breaking on 0.89

### ISSUE THREAD

**Issue by shellux** [Devotics/heatzy-home-hassistant#1]
Bonjour,

Avec la derniere mises a jour de Home Assistant, le module Heatzy ne ce lance plus.

`Error loading custom_components.climate.heatzy. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/heatzy/__init__.py", line 11, in <module>
    from .pilote_v1 import HeatzyPiloteV1Thermostat
  File "/config/custom_components/climate/heatzy/pilote_v1.py", line 1, in <module>
    from homeassistant.components.climate import (STATE_COOL, STATE_ECO,
ImportError: cannot import name 'STATE_COOL' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)`

Je pense que ca viens des modification importé depuis a 0.87:
https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

Je vais voir si je peux modifier de mon coté la structure pour l'adapter

**Comment by shellux** [comment]
Bon aprés un rolback de home assistant su la version 88.02, il y a en effet un message d'avertissement: `Integrations need to be in their own folder. Change climate/heatzy.py to heatzy/climate.py. This will stop working soon.`
